spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
  datasource:
    password: ratil123
    username: root
    url: jdbc:mysql://localhost:3306/anime_crawler?useSSL=false&serverTimezone=CTT&character=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: ratil123
    jedis:
      pool:
        max-active: 100
        max-idle: 10
    timeout: 60000
    

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: warn
    org.springframwork.boot: info
    top.ratil.animecrawler.task: info
  path: /www/wwwroot/animecrawler/log
